### ISSUE TITLE
Lack of automatic (cron) tracking update

### ISSUE THREAD

**Issue by e-gaulue** [PrestaShop/dpdfrance#22]
We have everything needed:
- parcel number
- tracking server URL (rather slow by the way...)

We just need to look for every orders associated to DPD carrier in given order states if they are:
- handled by DPD
- delivered

Easy to do, main inconvinience: server slow, http answer. A kind of web service would be more appreciated. Presently we have to do it ourselves by hand.

Regards,

**Comment by mbrentini** [comment]
Thank you for your message, this functionality and many more features are under development, which will be included in a future release near Q1 2016.

Unfortunately, we don't have everything needed, indeed we need a webservice access for tracking and sufficient server performance to handle 12k+ tracing requests at nearly the same time.

Thank you for your patience !

Best Regards,

**Comment by mbrentini** [comment]
Hi,

This functionality was finally added to version 5.2.1 of module.
