### ISSUE TITLE
No more carriers available when installing and a «Boutiques France» zone already exists.

### ISSUE THREAD

**Issue by ambroisemaupate** [PrestaShop/dpdfrance#23]
We experienced a «Aucun transporteur disponible» error when clicking on DPD promotional link on Prestashop admin home-page.
### How we managed to fix it
- We found that a «Boutiques France» zone already existed before we clicked on DPD module install link. Here is a SQL dump of `ps_zones` table before the bug occured:

``` sql
DROP TABLE IF EXISTS `ps_zone`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `ps_zone` (
  `id_zone` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(64) NOT NULL,
  `active` tinyint(1) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`id_zone`)
) ENGINE=InnoDB AUTO_INCREMENT=13 DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `ps_zone`
--

LOCK TABLES `ps_zone` WRITE;
/*!40000 ALTER TABLE `ps_zone` DISABLE KEYS */;
INSERT INTO `ps_zone` VALUES (1,'Europe',1),(2,'North America',1),(3,'Asia',1),(4,'Africa',1),(5,'Oceania',1),(6,'South America',1),(7,'Europe (out E.U)',1),(8,'Centrale America/Antilla',1),(9,'France',1),(10,'DOM',1),(11,'TOM',1),(12,'Boutiques France',1);
/*!40000 ALTER TABLE `ps_zone` ENABLE KEYS */;
UNLOCK TABLES;
```
- After installing DPD module the «Aucun transporteur disponible pour cette adresse» error occurs on carrier choice step.
- We had to rename «Boutique France» to «Boutique FR» zone
- Reinstall DPD module, then
- Uninstall DPD module.

It’s a really dangerous behaviour to directly install module on clicking on the promotional link on administration homepage. And it convey a very bad image of DPD carrier, especially if the module break our shop payment system.

You should fix that very quickly.

**Comment by mbrentini** [comment]
Hello @ambroisemaupate ,

As discussed on the phone, we need to separate the France country from the others within a specific French delivery zone. First we check if a zone name containing the "France" word exists, if so we'll reuse that zone. If not, we create a "France" zone and place the France country in it. This indeed affects existing carriers, so you'll just have to report your shipping rates to the newly created France zone.

We'll try to set zones differently in our next update :)

Best regards
