### ISSUE TITLE
Select pick-up from Prestashop backoffice

### ISSUE THREAD

**Issue by e-gaulue** [PrestaShop/dpdfrance#25]
Lots of orders are done with the client on the phone.

We use the backoffice order creation to do that and we would really need to be able to select "pick-up" from there.

**Comment by mbrentini** [comment]
Hello M. Gaulue,

Prestashop doesn't allow to display modules on the New Order page in the backoffice.

**Comment by e-gaulue** [comment]
Hi,

You are right, maybe it should be discuss with the Prestashop Team (that's a common and justified request). Do you know if that has already been discuss?

Regards,

**Comment by mbrentini** [comment]
Not discussed already, but since a lot of changes will occur with Prestashop 1.7, we will contact Prestashop during or after the release of a stable version.

**Comment by e-gaulue** [comment]
I think 1.7 will mostly provide unitary test.

Maybe a better workaround is to use a kind of "login as customer".

For the moment, I just changed the step we go on "Goto payment..." at the end of the order creation in the BO.

**Comment by mbrentini** [comment]
Hello,

This feature is still not integrable in 1.7, as the BO is 99% the same as 1.6.
