### ISSUE TITLE
JQMIGRATE: jQuery.fn.load() is deprecated

### ISSUE THREAD

**Issue by francoisromain** [PrestaShop/dpdfrance#26]
The jquery `.load(` function is deprectaed with jquery 3. 

Could you replace it with `.on('load',`?

thank you

**Comment by mbrentini** [comment]
Hi,

By default, Prestashop relies on jQuery 1.x.

We are required to respect current Prestashop standards, if you change jQuery version for your site, you will be required to make the accorgind modifications.

Best regards

**Comment by francoisromain** [comment]
replacing the code above still work with jquery v.1…
